workflows:
  ios-workflow-id:
    name: iOS App Store Release Workflow
    
    environment:
      vars:
        # Store credentials in environment variables
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_USERNAME: $APP_STORE_CONNECT_USERNAME

      # Xcode-specific settings
      xcode: latest # Use the latest stable Xcode version
      cocoapods: default # Automatically install CocoaPods dependencies

    scripts:
      - name: Install dependencies
        script: |
          gem install bundler
          bundle install
          bundle exec pod install

      - name: Build iOS App for App Store Distribution
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme "Runner" \
          -configuration Release \
          -archivePath $HOME/output/Runner.xcarchive archive \
          -sdk iphoneos \
          -allowProvisioningUpdates \
          -destination "generic/platform=iOS"

      - name: Export Archive to IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $HOME/output/Runner.xcarchive \
          -exportPath $HOME/output \
          -exportOptionsPlist ios/ExportOptions.plist

      - name: Upload IPA to App Store Connect
        script: |
          bundle exec fastlane pilot upload --ipa $HOME/output/Runner.ipa \
          --username $APP_STORE_CONNECT_USERNAME \
          --skip_waiting_for_build_processing true

    artifacts:
      - $HOME/output/*.ipa
      - $HOME/output/*.xcarchive

    publishing:
      email:
        recipients:
          - your-email@example.com
