workflows:
  ios-workflow-id:
    name: iOS App Store Release Workflow

    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_USERNAME: $APP_STORE_CONNECT_USERNAME
      
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install system dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev libsqlite3-dev zlib1g-dev
          echo "System dependencies installed"

      - name: Install Bundler
        script: |
          gem install bundler
          echo "Bundler version: $(bundle -v)" # Output bundler version for debugging

      - name: Install dependencies using Bundler
        script: |
          # Use verbose output to troubleshoot
          bundle install --verbose || exit 1
          bundle exec pod install --verbose || exit 1

      - name: Build iOS App for App Store Distribution
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme "Runner" \
          -configuration Release \
          -archivePath $HOME/output/Runner.xcarchive archive \
          -sdk iphoneos \
          -allowProvisioningUpdates \
          -destination "generic/platform=iOS"

      - name: Export Archive to IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $HOME/output/Runner.xcarchive \
          -exportPath $HOME/output \
          -exportOptionsPlist ios/ExportOptions.plist

      - name: Upload IPA to App Store Connect
        script: |
          bundle exec fastlane pilot upload --ipa $HOME/output/Runner.ipa \
          --username $APP_STORE_CONNECT_USERNAME \
          --skip_waiting_for_build_processing true

    artifacts:
      - $HOME/output/*.ipa
      - $HOME/output/*.xcarchive

    publishing:
      email:
        recipients:
          - your-email@example.com
